--- # installing httpd, ntpd & tree packages using ansible-pull command
- hosts: localhost
  user: ansible
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
          - yum:
            name:
              - httpd
              - ntp
              - tree
            state: present
