--- # installing httpd, ntpd & tree packages using ansible-pull command
- hosts: db
  user: ansible
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
         - name: installing packages 
           yum:
             name:
               - httpd
               - ntp
               - tree
             state: present
