--- #continously making changes to website
- hosts: localhost
  become: yes
  gather_facts: yes
  connection: ssh
  tasks:
        - name: creating file
          file:
                  dest: /var/www/html/index.html
                  state: touch

        - name: adding line to index.html file
          lineinfile:
                  dest: /var/www/html/index.html
                  line: hi

